# Generated by Django 5.0.4 on 2024-04-22 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_alter_episode_order_alter_message_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='stories.story'),
        ),
        migrations.AddField(
            model_name='story',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
