# Generated by Django 5.0.4 on 2024-04-22 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_alter_story_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='published',
            new_name='is_published',
        ),
    ]
