# Generated by Django 5.0.4 on 2024-04-22 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_rename_published_story_is_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='is_published',
            new_name='published',
        ),
    ]
