# Generated by Django 5.0.4 on 2024-04-22 21:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_rename_is_published_story_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='story_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
