# Generated by Django 5.0.4 on 2024-04-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_alter_story_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='story',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='story',
            name='views',
        ),
        migrations.AddField(
            model_name='story',
            name='views',
            field=models.ManyToManyField(blank=True, null=True, to='stories.ipaddress'),
        ),
    ]
