# Generated by Django 5.0.4 on 2024-05-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_alter_savedstory_options_remove_episode_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='message',
            name='order',
            field=models.FloatField(unique=True),
        ),
    ]
