# Generated by Django 5.0.4 on 2024-05-11 20:46

import stories.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0011_alter_message_options_alter_message_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True, validators=[stories.validators.validate_hex_color]),
        ),
    ]
