# Generated by Django 5.0.4 on 2024-05-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0012_character_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status_content',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='text_content',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
