# Generated by Django 5.0.4 on 2024-05-26 12:20

import stories.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0013_alter_message_status_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='color',
            field=models.CharField(default='#C39BD3', max_length=7, unique=True, validators=[stories.validators.validate_hex_color]),
            preserve_default=False,
        ),
    ]
