# Generated by Django 5.0.4 on 2024-06-01 13:55

import stories.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0014_alter_character_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='character',
            name='color',
            field=models.CharField(max_length=7, validators=[stories.validators.validate_hex_color]),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
