# Generated by Django 5.0.4 on 2024-06-11 22:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0015_alter_character_options_alter_episode_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='audio_content',
            field=models.FileField(blank=True, null=True, upload_to='message_audios', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav'])]),
        ),
        migrations.AlterField(
            model_name='message',
            name='image_content',
            field=models.ImageField(blank=True, null=True, upload_to='message_images', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='message',
            name='order',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='video_content',
            field=models.FileField(blank=True, null=True, upload_to='message_videos', validators=[django.core.validators.FileExtensionValidator(['mp4'])]),
        ),
    ]
